import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import {ReactNode} from "react";
import Provider from "@/components/Provider";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">

    <body className={inter.className}>
    <Provider>
        <Header/>
        <div className={'container m-auto'}>
            {children}
        </div>
    </Provider>
        </body>
    </html>
  )
}
